@startuml
autoactivate on
hide footbox
skinparam sequenceParticipant underline

title CPP RunShapes "read" Function With Iterators

participant ":RunShapes" as rs

activate rs

create "collection:ShapeCollection" as collection
rs -> collection: new
return

create "it:istream_iterator<Shape*>"
rs -> "it:istream_iterator<Shape*>": new(ins)
return

create "end:istream_iterator<Shape*>"
rs -> "end:istream_iterator<Shape*>": new(ins)
return

participant ":ShapeFactory" as sf

loop it != end
rs -> "it:istream_iterator<Shape*>": operator*() [dereference]
    "it:istream_iterator<Shape*>" -> sf: operator>>(ins, s)
        sf -> sf: createShape(name)
        return s
        alt s is not null
            create "s:Shape*" as sptr
            sf -> sptr: new()
            return
            sf -> sptr: read(ins)
            return
        else discard the rest of the line
        end
    return
return  s
end

opt s is not null
    rs -> collection: emplace_back(s)
    create ":unique_ptr<Shape>"
        collection -> ":unique_ptr<Shape>": new(s)
        return
    return
    rs -> "it:istream_iterator<Shape*>": operator++() [post increment]
    return
end

rs -> "it:istream_iterator<Shape*>" !!: delete
rs -> "end:istream_iterator<Shape*>" !!: delete

deactivate rs

@enduml

