[package]
name = "tictactoe"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
eyre = "0.6.12"
hamcrest2 = "*"
itertools = "0.13.0"
thiserror = "2.0.3"

[dev-dependencies]
rstest = "0.21.0"
